version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXTAUTH_SECRET: "0Xw0YATU1D3rRHpaBhE3DsccN7a+3K9N4QTtdUQ/TzI="
      NEXTAUTH_URL: "http://localhost:3000"
      BACKEND_URL: "http://0.0.0.0:80"
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:8000"
      DEBUG: "true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: ["npm", "run", "dev"]
    env_file:
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
